networks:
  default:
    name: grist_net

  shared:
    external: true

volumes:
  grist_data:
    name: grist_data

services:
  redis:
    container_name: redis
    image: redis:8-alpine

  grist: # port 8484
    container_name: grist
    image: gristlabs/grist:latest
    restart: unless-stopped
    environment:
      REDIS_URL: redis://redis
    volumes:
      - grist_data:/persist
    depends_on:
      - redis
    networks:
      - default
      - shared

