networks:
  default:
    name: expenses_net

  shared:
    external: true

services:
  expenses:
    container_name: expenses
    image: expenses:latest
    build:
      context: .
    environment:
      GRIST_URL: http://grist:8484
      GRIST_DOC_ID: ${GRIST_DOC_ID}
      GRIST_API_KEY: ${GRIST_API_KEY}
    networks:
      - default
      - shared
