networks:
  default:
    name: expenses_net

  shared:
    external: true

services:
  expenses:
    container_name: expenses
    image: bosstnp/expenses:latest
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
    environment:
      GRIST_URL: http://gristguard:8484
      GRIST_DOC_ID: ${GRIST_DOC_ID}
      GRIST_API_KEY: ${GRIST_API_KEY}
    networks:
      - default
      - shared
