networks:
  default:
    name: grist_net

  shared:
    external: true

volumes:
  grist_data:
    name: grist_data

services:
  redis:
    container_name: redis
    image: redis:8-alpine

  grist: # port 8484
    container_name: grist
    image: gristlabs/grist:stable
    restart: unless-stopped
    environment:
      REDIS_URL: redis://redis
      GRIST_SINGLE_ORG: ${GRIST_SINGLE_ORG}
      GRIST_FORCE_LOGIN: ${GRIST_FORCE_LOGIN}
      GRIST_SESSION_SECRET: ${GRIST_SESSION_SECRET}
      GRIST_DOCS_MINIO_BUCKET: ${GRIST_DOCS_MINIO_BUCKET}
      GRIST_DOCS_MINIO_ENDPOINT: ${GRIST_DOCS_MINIO_ENDPOINT}
      GRIST_DOCS_MINIO_ACCESS_KEY: ${GRIST_DOCS_MINIO_ACCESS_KEY}
      GRIST_DOCS_MINIO_SECRET_KEY: ${GRIST_DOCS_MINIO_SECRET_KEY}
      GRIST_DOCS_MINIO_BUCKET_REGION: ${GRIST_DOCS_MINIO_BUCKET_REGION}
    volumes:
      - grist_data:/persist
    depends_on:
      - redis
    networks:
      - default
      - shared

  gristguard:
    container_name: gristguard
    image: bosstnp/gristguard:latest
    environment:
      PORT: 8484
      GRIST_ENDPOINT: http://grist:8484
      GRIST_API_KEY: ${GRISTGUARD_GRIST_API_KEY}
      GRIST_DOCUMENT_ID: ${GRISTGUARD_GRIST_DOCUMENT_ID}
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
    depends_on:
      - grist
    networks:
      - default
      - shared

